<?php

namespace Proxies\__CG__\WebPlatform\AseagleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \WebPlatform\AseagleBundle\Entity\Transaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'buyerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'productId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'sellerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'buyerAskQuantity', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'sellerQuotation', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'negotiation', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'status', 'product', 'buyer', 'seller');
        }

        return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'buyerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'productId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'sellerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'buyerAskQuantity', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'sellerQuotation', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'negotiation', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Transaction' . "\0" . 'status', 'product', 'buyer', 'seller');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Transaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyerId($buyerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyerId', array($buyerId));

        return parent::setBuyerId($buyerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyerId', array());

        return parent::getBuyerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductId($productId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductId', array($productId));

        return parent::setProductId($productId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', array());

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellerId($sellerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellerId', array($sellerId));

        return parent::setSellerId($sellerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellerId', array());

        return parent::getSellerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyerAskQuantity($buyerAskQuantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyerAskQuantity', array($buyerAskQuantity));

        return parent::setBuyerAskQuantity($buyerAskQuantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyerAskQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyerAskQuantity', array());

        return parent::getBuyerAskQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setSellerQuotation($sellerQuotation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSellerQuotation', array($sellerQuotation));

        return parent::setSellerQuotation($sellerQuotation);
    }

    /**
     * {@inheritDoc}
     */
    public function getSellerQuotation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSellerQuotation', array());

        return parent::getSellerQuotation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNegotiation($negotiation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNegotiation', array($negotiation));

        return parent::setNegotiation($negotiation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNegotiation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNegotiation', array());

        return parent::getNegotiation();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\WebPlatform\AseagleBundle\Entity\Product $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyer(\WebPlatform\AseagleBundle\Entity\User $buyer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyer', array($buyer));

        return parent::setBuyer($buyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyer', array());

        return parent::getBuyer();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeller(\WebPlatform\AseagleBundle\Entity\User $seller = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeller', array($seller));

        return parent::setSeller($seller);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeller()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeller', array());

        return parent::getSeller();
    }

}
