<?php

namespace Proxies\__CG__\WebPlatform\AseagleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Follow extends \WebPlatform\AseagleBundle\Entity\Follow implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'followerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'followedTraderId', 'followed_trader', 'follower');
        }

        return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'followerId', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Follow' . "\0" . 'followedTraderId', 'followed_trader', 'follower');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Follow $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFollowerId($followerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFollowerId', array($followerId));

        return parent::setFollowerId($followerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowerId', array());

        return parent::getFollowerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFollowedTraderId($followedTraderId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFollowedTraderId', array($followedTraderId));

        return parent::setFollowedTraderId($followedTraderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowedTraderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowedTraderId', array());

        return parent::getFollowedTraderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFollowedTrader(\WebPlatform\AseagleBundle\Entity\User $followedTrader = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFollowedTrader', array($followedTrader));

        return parent::setFollowedTrader($followedTrader);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowedTrader()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowedTrader', array());

        return parent::getFollowedTrader();
    }

    /**
     * {@inheritDoc}
     */
    public function setFollower(\WebPlatform\AseagleBundle\Entity\User $follower = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFollower', array($follower));

        return parent::setFollower($follower);
    }

    /**
     * {@inheritDoc}
     */
    public function getFollower()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollower', array());

        return parent::getFollower();
    }

}
