<?php

namespace Proxies\__CG__\WebPlatform\AseagleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \WebPlatform\AseagleBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'picture', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'category_id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'owner_id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'product_detail_1', 'category', 'owner', 'product_tags', 'transactions');
        }

        return array('__isInitialized__', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'title', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'picture', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'price', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'category_id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'owner_id', '' . "\0" . 'WebPlatform\\AseagleBundle\\Entity\\Product' . "\0" . 'product_detail_1', 'category', 'owner', 'product_tags', 'transactions');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($picture));

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryId($categoryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryId', array($categoryId));

        return parent::setCategoryId($categoryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryId', array());

        return parent::getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnerId($ownerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnerId', array($ownerId));

        return parent::setOwnerId($ownerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnerId', array());

        return parent::getOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductDetail1($productDetail1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductDetail1', array($productDetail1));

        return parent::setProductDetail1($productDetail1);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductDetail1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductDetail1', array());

        return parent::getProductDetail1();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\WebPlatform\AseagleBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(\WebPlatform\AseagleBundle\Entity\User $owner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', array($owner));

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', array());

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductTag(\WebPlatform\AseagleBundle\Entity\ProductTag $productTags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductTag', array($productTags));

        return parent::addProductTag($productTags);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductTag(\WebPlatform\AseagleBundle\Entity\ProductTag $productTags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductTag', array($productTags));

        return parent::removeProductTag($productTags);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductTags', array());

        return parent::getProductTags();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\WebPlatform\AseagleBundle\Entity\Transaction $transactions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', array($transactions));

        return parent::addTransaction($transactions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransaction(\WebPlatform\AseagleBundle\Entity\Transaction $transactions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransaction', array($transactions));

        return parent::removeTransaction($transactions);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactions', array());

        return parent::getTransactions();
    }

}
